.github/workflows/build.yml
Use GitHub Actions to try to configure CI for various targets.  Add an
initial build for Windows as a quick and dirty test as this is the more
complicated platform.
=> CI: add initial pass at Windows CI

CMakeLists.txt, Tools/JSObjects/CMakeLists.txt, Tools/RegsGen2/CMakeLists.txt
Use the global C++ standards for the project rather than individually
setting the properties on the targets.
=> build: use global CMake settings

CMakeLists.txt, Tools/JSObjects/CMakeLists.txt, Tools/RegsGen2/CMakeLists.txt
Explicitly specify the languages the projects use and use the global language
standard specification.
=> build: specify languages for projects

CMakeLists.txt
Update the CMake requirement to 3.13+ and use the modern form to prevent
the linked libraries from over-propagating.  Convert the linker options
to use `target_link_options` rather than `target_link_libraries`.
=> build: use modern `target_link_libraries` form

Sources/Host/POSIX/File.cpp
When building with gcc 9, the signed comparisons here prevent building.  Add
some `static_cast`s  to deal with the type conversion.
=> POSIX: add some casts for `-Werror=sign-compare`

Sources/Host/Common/Socket.cpp, Sources/Host/Linux/ProcFS.cpp
When building with GCC 9.3, the `strncpy` is flagged as a possible truncation as
we use the size of the destination for the `strncpy` which expects space for the
trailing nul.  However, we are working with a fixed size buffer, and so prefer
the use of `memcpy` instead.
Take the opportunity to explicitly write the leading nul-character for the unix
path.
=> Host: repair the build with `-Werror=stringop-truncation`

Sources/Target/Linux/Process.cpp
When building with GCC 9.3, the following maybe uninitialized path is identified:
~~~
Sources/Target/Linux/Process.cpp: In member function ‘virtual ds2::ErrorCode ds2::Target::Linux::Process::wait()’:
Sources/Target/Linux/Process.cpp:328:51: error: ‘tid’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
328 |   if (!(WIFEXITED(status) || WIFSIGNALED(status)) || tid != _pid) {
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
~~~
Although the `DS2ASSERT` exists above the loop, gcc does not propagate the
information through LICM which results in the path being misflagged.  Convert to
`do { } while` instead of `while { }` to indicate that we expect at least one
iteration through the loop.
=> Target: repair the build for `-Werror=maybe-uninitialized`

Headers/DebugServer2/Host/Windows/ExtraWrappers.h
When `WaitForDebugEventEx` is not available (e.g. building for MinGW),
simply fall back to `WaitForDebugEvent` instead.  Otherwise, expect the
headers to declare the interface.
=> Windows: opt into Unicode with `WaitForDebugEventEx`

Headers/DebugServer2/Host/Windows/ExtraWrappers.h
This check is needed outside of the UWP case as MinGW does not provide
this interface.
=> Windows: `WaitForDebugEventEx` should always be checked

CMakeLists.txt
This breaks the build on MinGW currently.  Furthermore, this is a horrible
workaround.  We should simply build with debug information and symbolicate with
the debug information.
=> build: remove `-rdynamic` hack

Sources/Target/Windows/Thread.cpp
Annotate the switch with a fallthrough to indicate that it is expected.  This
repairs the build with `-Wrror=implicit-fallthrough`.
~~~
Sources/Target/Windows/Thread.cpp: In member function 'virtual void ds2::Target::Windows::Thread::updateState(const DEBUG_EVENT&)':
Headers/DebugServer2/Utils/Log.h:62:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
62 |   ds2::Log(ds2::kLogLevel##LVL, nullptr, FUNCTION_NAME, __VA_ARGS__)
|   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sources/Target/Windows/Thread.cpp:178:7: note: in expansion of macro 'DS2LOG'
178 |       DS2LOG(Warning, "unsupported exception code: %lx",
|       ^~~~~~
Sources/Target/Windows/Thread.cpp:181:5: note: here
181 |     case STATUS_INVALID_DISPOSITION:
|     ^~~~
~~~
=> Target: repair `-Werror=implicit-fallthrough`

CMakeLists.txt, Headers/DebugServer2/Host/Windows/ExtraWrappers.h
These functions are not currently used in the implementation.  Remove them to
reduce the configure time.  Additionally, since the minimum version of Windows
which makes sense to support currently is Windows 10 (with the older Windows now
being EOL'ed), we can likely reduce the checks and shims further.  This removes
the easiest cases first.
=> Host: remove unnecessary Windows API checks and shims

CMakeLists.txt, Headers/DebugServer2/Host/Windows/ExtraWrappers.h
Remove some typedefinitions which were added to the ExtraWrappers shim header.
These types are unreferenced in the current codebase.
=> Host: remove some unnecessary type shims on Windows

CMakeLists.txt
Use the more modern CMake listing style which is more declarative than
building up the list by concatenating variables.
=> build: use a more declarative source list for ds2

Tools/RegsGen2/CMakeLists.txt
This avoids the creation of a temporary variable to list the sources.
Additionally, remove the extra flags which really are ideally passed through the
CI system for testing purposes to prevent build issues with future compilers.
=> RegsGen2: simplify the build rules

Headers/DebugServer2/Types.h, Sources/Host/Windows/Platform.cpp
This replaces the UID and GID fields with a `std::unique_ptr` instead of
the manual memory management.  This is required to remove the user
provided dtor so that the implicit copy constructor is synthesized.
Repairs the build with `-Werror=Wdeprecated-copy-dtor`.
=> DebugServer2: use `std:unique_ptr<SID>` on Windows

Headers/DebugServer2/Types.h
Ensure that we have a valid SID when copying the SID.  This avoids an
invalid access of the SID.
=> DebugServer2: ensure that we have a valid SID before use

CMakeLists.txt, Headers/DebugServer2/Host/Windows/ExtraWrappers.h
This further trims the checked interfaces by removing everything which is listed
as being available on Desktop and UWP on MSDN.  This should reduce the configure
time for Windows and the dependency on the shims.
=> Host: remove additional interfaces

.github/workflows/build.yml
GitHub has updated the builders to VS2022, update the generator to use the
correct generator name to match that.
=> CI: bump GHA Windows MSVC builder to VS2022

Tools/JSObjects/Sources/libjson/qstring.c
This temporarily pre-processes away the implementation to avoid disabling a
warning when building with a newer compiler - `-Werror=unused-but-set-variable`.
=> JSObjects: remove partial implementation of method

Tools/RegsGen2/CMakeLists.txt, Tools/RegsGen2/getopt.c, Tools/RegsGen2/getopt.h, Tools/RegsGen2/main.cpp
This imports a static copy of a `getopt` implementation which enables the tool
to be built on Windows as well as Linux.  This is required to migrate towards
generating the register definitions at build time.
=> RegsGen2: import a `getopt` implementation

Tools/RegsGen2/Definitions.h, Tools/RegsGen2/FlagSet.cpp, Tools/RegsGen2/FlagSet.h, Tools/RegsGen2/RegisterSet.cpp, Tools/RegsGen2/RegisterTemplate.cpp, Tools/RegsGen2/RegisterTemplate.h, Tools/RegsGen2/main.cpp
Replace occurrences of `ssize_t` with some template metaprogramming to create
the equivalent signed type of `size_t` as `ssize_t` is a GNU extension rather
than a standard type.  This is needed to ensure that RegsGen2 is portable.
=> RegsGen2: avoid spelling `ssize_t`

Headers/DebugServer2/Core/CPUTypes.h
With C++11 and newer, it is permissible to have a trailing common on the
enumerator list.  Use this to make it easier to extend the definitions.
=> Core: add trailing commas to enums (NFC)

.github/workflows/build.yml
This adds the binaries for Windows, MinGW, and macOS to the results.  This
should make it easier to use the results.
=> CI: adjust build workflows to upload results

Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Host/Linux/PTrace.cpp, Sources/Target/POSIX/Process.cpp, Sources/Target/POSIX/Thread.cpp, Sources/main.cpp
Include missing headers for declarations that are referenced.  This was required
to build for rv64 with gcc and libstc++.
=> ds2: include additional headers

Headers/DebugServer2/Core/BreakpointManager.h, Headers/DebugServer2/Core/HardwareBreakpointManager.h, Headers/DebugServer2/Core/SoftwareBreakpointManager.h, Sources/Core/ARM/HardwareBreakpointManager.cpp, Sources/Core/ARM/SoftwareBreakpointManager.cpp, Sources/Core/BreakpointManager.cpp, Sources/Core/X86/HardwareBreakpointManager.cpp, Sources/Core/X86/SoftwareBreakpointManager.cpp
When selecting the size of the breakpoint, the target requires knowledge
of the breakpoint location to make the size determination.  This will be
used in the RISCV support subsequently.
=> Core: wire through the address for breakpoint selection

Sources/Host/Linux/PTrace.cpp
This changes the condition for the check to be the inverse: assume no hardware
support unless otherwise known.  This should enforce the safe path on all the
targets which matches the default behaviour of ptrace.
=> Host: assume no hardware support for single stepping by default

Headers/DebugServer2/Utils/Enums.h, Headers/DebugServer2/Utils/HexValues.h, Headers/DebugServer2/Utils/MPL.h, Headers/DebugServer2/Utils/ScopedJanitor.h, Headers/DebugServer2/Utils/SwapEndian.h
This makes the headers more standalone and easier to work with.  These changes
would be needed to enable modular builds.
=> Headers: add some missing includes

CMakeLists.txt
The default behaviour of the C++ standard template library on MSVC is to enable
exceptions.  However, because we do not use exceptions, ensure that we indicate
that exceptions should be disabled.
=> build: disable STL exceptions on MSVC

Headers/DebugServer2/Utils/Enums.h
This protects from redefinitions should the header be included in more than one
location.
=> Headers: add a missing `#pragma once`

Sources/Target/Windows/Thread.cpp
`[[fallthrough]]` was standardized in C++17, use that over
`[[gnu::fallthrough]]`.  This should silence a wanring on Windows.
=> Windows: use C++ standard attribute

Sources/Core/X86/HardwareBreakpointManager.cpp
Explicitly type the constant `1` to an `unsigned long long` during the shift
operation to construct the mask against a `uint64_t`.  This should silecne a
warning on 32-bit Windows.
=> X86: silence a warning on Windows x86

Headers/DebugServer2/Utils/CompilerSupport.h, Sources/Core/X86/HardwareBreakpointManager.cpp, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/Host/POSIX/ProcessSpawner.cpp
With C++17, we have the `[[fallthrough]]` attribute to indicate a fallthrough on
a switch case.  Adopt that consistently and apply it to a few sites that were
missing the attribute.
=> Replace `DS2_FALLTHROUGH` with standard `[[fallthrough]]`

.gitignore, CMakeLists.txt, Definitions/RISCVnnn.json, Headers/DebugServer2/Architecture/CPUState.h, Headers/DebugServer2/Architecture/RISCV/CPUState.h, Headers/DebugServer2/Architecture/RISCV/SoftwareSingleStep.h, Headers/DebugServer2/Base.h, Headers/DebugServer2/Core/CPUTypes.h, Headers/DebugServer2/Utils/Log.h, Sources/Architecture/RISCV/SoftwareSingleStep.cpp, Sources/Core/CPUTypes.cpp, Sources/Core/RISCV/HardwareBreakpointManager.cpp, Sources/Core/RISCV/SoftwareBreakpointManager.cpp, Sources/Host/Common/Platform.cpp, Sources/Host/Linux/RISCV/PTraceRISCV.cpp, Sources/Support/POSIX/ELFSupport.cpp, Sources/Target/Common/RISCV/ProcessBaseRISCV.cpp, Sources/Target/Linux/RISCV/ProcessRISCV.cpp, Sources/Target/POSIX/Thread.cpp
This adds the rv{32,64,128} skeleton in place so that we can start adding the
necessary architectural support.
=> RISCV: add skeleton infrastructure for RISCV

Sources/Architecture/RISCV/SoftwareSingleStep.cpp, Sources/Target/Linux/RISCV/ProcessRISCV.cpp
This cleans up a few warnings and build issues identified with a build of ds2 on RISCV with clang/libc++ .
=> Sweep up some lingering warnings from clang/libc++

CMakeLists.txt, Sources/main.cpp
This adds in a new connection type: character device.  This allows use
of DS2 with a serial port much as is possible with gdbserver.
=> ds2: add support for serial port connections

BUILD, CMakeLists.txt, Headers/DebugServer2/Host/POSIX/HandleChannel.h, Sources/Host/POSIX/HandleChannel.cpp, Sources/main.cpp
Introduce a new `HandleChannel` type that creates a channel from a handle.  This
allows us to create a channel to a serial port device.  Wire this up in main to
get a channel to the physical device, enabling serial port support.
=> Host: support character devices on POSIX platforms

Tools/JSObjects/CMakeLists.txt
Ignore `unused-but-set-variable` as an error in generated code which now is triggered on MinGW64.
=> build: ignore warning in generated code

Sources/Utils/POSIX/FaultHandler.cpp
Glibc 2.34+ renames `SIGSTKSZ` to a `sysconf` query.  Use that to dynamically query and allocate the buffer as a dynamically allocated static managed buffer.
=> POSIX: adjust the alt stack buffer

Headers/DebugServer2/Types.h
`GetSidSubAuthorityCount` returns a `PUCHAR`, adjust the storage to use the appropriate type rather than the `DWORD` which widens the result unnecessarily (and subsequently needs to be truncated for the calls in the construction of the SID.
=> DS2: adjust type for `GetSidSubAuthorityCount` result

Headers/DebugServer2/Core/SoftwareBreakpointManager.h, Sources/Core/ARM/SoftwareBreakpointManager.cpp, Sources/Core/RISCV/SoftwareBreakpointManager.cpp, Sources/Core/X86/SoftwareBreakpointManager.cpp
The parameter `type` in the software breakpoint manager indicates the length of the instruction sequence.  Rename the parameter to `size` to reflect that.
=> Core: rename a parameter (NFC)

CMakeLists.txt, Sources/Utils/Backtrace.cpp
```
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b119d05
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b11aada
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b11a52c
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b09218c
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b091897
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b0d5bed
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b0c486b
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b0c525e
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b100538
[22776][ds2::Utils::PrintBacktraceEntrySimple] ERROR  : 0x00007ff72b0530ba …
```
=> ds2: symbolize and emit file:line information in backtraces on windows.

Sources/Target/Windows/Process.cpp
This adds a breakpoint stub for Windows ARM64.  The following instruction sequence is used:
~~~
brk	#0xf000
ldr	x16, #8
br	x16
...
~~~
Windows ARM64 uses `brk #0xf000` as the debug interrupt sequence, and we follow the same pattern as the other architectures to simplify the writing of the stub.  The following would be shorter, but more complicated to emit:
~~~
brk	#0xf000
ldr	x16, :got:RtlExitUserThread
ldr	x16, [x16, :got_lo12:RtlExitUserThread]
br	x16
~~~
=> Windows: add breakpoint stub for Windows ARM64

Tools/JSObjects/CMakeLists.txt
- Avoid an unnecessary list construction for the `jsobjects` library.
- Collapse some conditions rather than check them multiply.
- Prefer to use `target_compile_definitions` over `target_compile_options` for CPP macro definitions.
- Some minor whitespace fixes.
=> JSObjects: clean up the build rules somewhat

.github/workflows/build.yml
This silences a warning due to deprecation of node 12.
=> GHA: update to actions/{checkout,upload-artifact} v4

.github/workflows/build.yml
The [macos-latest runner ](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources )is M1 ARM only, but ds2 doesn't support Darwin on ARM yet. Until that support is implemented, we can run on macos-13 to target x86 and keep the build green.
=> update the macos build to run on macos-13 instead of latest

.github/workflows/build.yml
Enable automated ds2 Android builds on Windows for all supported architectures.
It turns out the Windows runner images already have [Android SDK and NDK installed](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#Android), so there was no reason to add any custom actions to install NDK tools. Cmake automatically finds the NDK from the environment when `CMAKE_SYSTEM_NAME=Android`. 
**Test Plan**
Manually invoked the build action on my ds2 branch and inspected [the logs](https://github.com/andrurogerz/ds2/actions/runs/9867312773).
fixes compnerd/ds2#82
=> android: add GHA to build Android versions of ds2 using Windows NDK

.github/workflows/build.yml
This makes it easier to see at a glance what options are being passed to the cmake invocation during the configure phase.
=> GHA: split the CMake invocation into line per option

.github/workflows/test.yml
Currently, building clang + lldb from llvm-project in the test work flow builds a total of **5270** targets. This change reduces the scope to only build targets needed to run the lldb tests from an x86 host against an Android emulator.
Specifically:
* Filtering `LLVM_TARGETS_TO_BUILD` to `X86` reduces total targets built to **4905**
* Explicitly building only the `tools/lldb/test/API/lldb-api-test-deps` target further reduces the total targets build to **4156**
This reduction should improve throughput and reduce disk usage of the `Build lldb` step in the test workflow.
=> [android] minimize llvm build to only what is required for running the lldb API tests

.github/workflows/test.yml
The sccache key for the llvm/lldb build should include the architecture of the host (runner) not the target.
=> [android] fix the sccache tag

.github/workflows/build.yml, CMakeLists.txt
Adds a new `DS2_REGSGEN2` CMake variable to manually specify the RegsGen2 executable invoked during the DS2 build. If the variable is not specified it falls-back to the previous behavior of building it as an external project.
Update GitHub builds for Windows, MinGW, and Android to pre-build the RegsGen2 executable in a separate `windows_tools` step which properly uses the VS toolchain.
=> allow RegsGen2 executable to be manually specified

.github/workflows/build.yml, .github/workflows/nightly.yml, .github/workflows/test.yml
Adds a new GHA workflow to run the existing build and test workflows every night at 8:45 PM.
On success, create a new tag with the format "nightly-YYYY-MM-DD".
Manually invoked the workflow [here](https://github.com/andrurogerz/ds2/actions/runs/10188630108).
Validated scheduling of the full workflow on my fork [here](https://github.com/andrurogerz/ds2/actions/runs/10205543363). The [tag](https://github.com/andrurogerz/ds2/releases/tag/nightly-2024-08-01) was created successfully.
=> [gha] nightly build/test/tag workflow

CMakeLists.txt
These variables are reserved by CMake to be user-controlled. We were previously modifying these to inject flags for the sanitizer and coverage builds. Use `add_compile_options` to control the default global options for all subdirectories. This allows the user to continue to properly control the C/C++ compile options.
=> build: reduce altering `CMAKE_{C,CXX}_FLAGS`

CMakeLists.txt
There are builtin variables in CMake that identify the platform that is being built for. Prefer to use the builtin identification of the host rather than building custom build rules for that.
=> build: replace use of custom variable names

Sources/GDBRemote/Session.cpp
The flag mapping for `vFile:open:` commands implemented in `Session::ConvertOpenFlags` was completely wrong for LLDB mode. The actual flag definitions are found [here](https://github.com/llvm/llvm-project/blob/main/lldb/include/lldb/Host/File.h). I don't think this ever worked unless the values were changed in lldb since this was implemented.
The miss-mapping caused a large number of the lldb tests to fail when run against ds2 on Linux because it couldn't create + write new files.
=> [bugfix] propertly handle vFile:open: flags

CMakeLists.txt
Rather than modifying `CMAKE_EXE_LINKER_FLAGS` directly apply the changes to the only executable target. Additionally, perform the linker option handling after the executable is added to the build.
=> build: address TODO for linker flag handling

README.md
Use the new GitHub flavoured markdown extension to render a note rather than attempting to format that manually.
=> docs: use GFM notes

CMakeLists.txt
When building for Windows, we define the minimum Windows version that we run on as Windows Vista, exclude the `MIN` and `MAX` macros as they conflict with `std::min` and `std::max`, and minimise the windows type definitions with `WIN32_LEAN_AND_MEAN`. Add the definitions in a single invocation.
=> build: simplify and unify macros for Windows

.github/workflows/build.yml
Use GitHub caching to speed up the test-android test job, which is the long-pole in the ds2 Build and Test workflow. It will save us a couple of minutes per run.
Uses caching in two places:
1. Cache the NDK. Since the same one is installed every run, it saves some time to keep it in the cache rather than download from Google.
2. Cache emulator image, device, and boot state. Caching this way is suggested in the [documentation](ReactiveCircus/android-emulator-runner) for ReactiveCircus/android-emulator-runner.
Ran the job twice and confirmed caches are created on the first run and are reused on the second run.
=> [gha] cache Android NDK and emulator in test workflow

.github/workflows/build.yml
This change decreases the time for running android tests by running them in parallel sets, with the "functionalities" tests being the largest set.
Also has the nice side-effect of making the test logs short enough to fit entirely in the GitHub web UI for each job so results can be viewed without downloading the full log archive.
=> [gha] split android test into 4 parallel jobs

Sources/Target/Linux/Process.cpp
The POSIX implementation of `Process::isAlive()` relies on successfully calling `kill(pid, 0)` to validate the target process' PID. This call fails with `EPERM` when ds2 is running in an Android app sandbox (at least newer Android versions).
Fix the issue by instead checking that `/proc/PID` exists. Perform this check only in the Linux override of `Process::isAlive()` since using procfs is not portable. There is no reason to scope the change to be Android-only, though, since it will work on any Linux system.
Since it doesn't show up here, the implementation of `super::isAlive()` that this PR replaces is [here](https://github.com/compnerd/ds2/blob/main/Sources/Target/POSIX/Process.cpp#L73).
It is worth noting that any solution to validate a PID is best-effort and is inherently racy. We …
=> [android] use procfs to check pid validity

CMakeLists.txt, Sources/Utils/POSIX/FaultHandler.cpp, Tools/JSObjects/CMakeLists.txt
I wanted to verify some Linux-specific changes don't break other platforms and found that ds2 doesn't currently build on FreeBSD 14.0. These patches address the issues encountered.
The most noteworthy change is the addition of `file(MAKE_DIRECTORY)` calls to the `RegsGen2` steps. This step was failing on FreeBSD because the directories did not already exist. Not sure why it succeeds on other platforms, but the `MAKE_DIRECTORY` addition should be harmless when not needed.
Built on VM running 14.0-RELEASE-p10.
Launched ds2 on FreeBSD in platform mode, verified lldb can connect.
=> [freebsd] fix the freebsd build

CMakeLists.txt, Sources/Utils/Backtrace.cpp
Add support to print ds2 backtraces on Android from the signal handler to diagnose crashes and fatal errors in DS2 itself.
* Reuse the existing backtrace plumbing and implement only the glibc `backtrace` functionality missing on Android
* Log  the module-relative address of each stack frame in addition to the existing information.
No backtraces are currently logged when DS2 crashes or encounters a fatal error on Android because `ds2::utils::PrintBacktrace` function is stubbed-out on platforms without glibc. Instead of glibc, Android provides  `libunwind` in the NDK exposed in the `unwind.h` header.
Manually verified mostly complete backtraces are emitted from signal handler context during a ds2 crash on a Debug. Verified with ds2 built for 4 Android ABIs. x86, x86_64, armeabi-v7a, and …
=> [android]  print backtraces on ds2 crashes/errors

Headers/DebugServer2/GDBRemote/DummySessionDelegateImpl.h, Headers/DebugServer2/GDBRemote/PlatformSessionImpl.h, Headers/DebugServer2/GDBRemote/SessionDelegate.h, Headers/DebugServer2/GDBRemote/Types.h, Headers/DebugServer2/Host/File.h, Headers/DebugServer2/Host/Platform.h, Headers/DebugServer2/Support/POSIX/ELFSupport.h, Headers/DebugServer2/Types.h, Sources/GDBRemote/DummySessionDelegateImpl.cpp, Sources/GDBRemote/PlatformSessionImpl.cpp, Sources/GDBRemote/Session.cpp, Sources/GDBRemote/Structures.cpp, Sources/Host/Darwin/Platform.cpp, Sources/Host/FreeBSD/Platform.cpp, Sources/Host/Linux/Platform.cpp, Sources/Host/POSIX/File.cpp, Sources/Host/Windows/File.cpp, Sources/Host/Windows/Platform.cpp, Sources/Support/POSIX/ELFSupport.cpp
Properly respond to the GDB `qModuleInfo` packet, defined [here](https://lldb.llvm.org/resources/lldbgdbremote.html#qmoduleinfo-module-path-arch-triple), in the DS2 platform session.
* Implement basic support to parse the build ID out of an ELF executable file
* Define a new `GetExecutableFileBuildID` method in the `Host::Platform` interface and implement a Linux and FreeBSD version based on the new ELF support to fetch build ID
* Define a new `fileSize` method in the `Host::File` interface and implement a POSIX version based on `stat`
* Define a new `onQueryModuleInfo` method in the `Session` interface and implement it in the platform session using the new file size and executable file build ID implementations
If deemed important, we can eventually implement …
=> [android] implement support for `qModuleInfo` packet

BUILD
This was recently added to the CMake build system but was not replicated to the bazel build. Attempt to bring this into parity. While the Darwin ARM64 port is incomplete, this allows us to maintain build system parity.
=> build: introduce bazel support for Darwin ARM64 builds

.github/workflows/build.yml
Add arm and aarch64 cross-compilation to the existing linux build job
=> [gha] cross compile arm and aarch64 for Linux

Sources/main.cpp
On Fedora 40, `getaddrinfo()` resolves host name * to 0.0.0.0. However, on Android it does not, which leads to a number of lldb tests failling when run against a ds2 server. This change makes explicitly remaps the name prior to calling `getaddrinfo()` to ensure the most compatibility. On its own, this change does not enable more lldb tests to pass, but it is required for some upcoming changes to work when run against an Android target.
This change matches the behavior of lldb-server, which was added (back) in llvm/llvm-project@f57453aece3e1dc56ce00a29ec6612d33e521c88 to address similar test failures.
=> explicitly map host name of * to 0.0.0.0 for compatibility

Sources/GDBRemote/Session.cpp
The changes made in compnerd/ds2@30b6a55445e28b52004648ed568b22379d6c5944 inadvertently dropped support for append mode in `vFile:open`. This PR adds back support.
With this change and some other local patches, the following lldb test cases now pass on Android and Linux:
```
TestGdbRemotePlatformFile.TestGdbRemotePlatformFile.test_platform_file_rdwr_append_llgs
TestGdbRemotePlatformFile.TestGdbRemotePlatformFile.test_platform_file_wronly_append_llgs
```
These tests will be re-enabled once this change and several others are merged.
=> properly support append mode with the `vFile:open` packet

.github/workflows/build.yml, Sources/Host/FreeBSD/Platform.cpp
The FreeBSD build was silently failing for a week or so but the GitHub build job was succeeding anyway. This looks like a quirk in the `vmactions/freebsd-vm`  action, where it reports the exit code of the last command run. This PR ensures the last command run is actually the `cmake --build` command.
* Move the `tar` command for the build output out of the VM and back to the job runner to ensure the last command run in the VM is `cmake --build`.
* Fix the build error introduced by compnerd/ds2@0cf4f7498ed84e321c5b4f77be2aa190385add15 by renaming FreeBSD's `Platform::GetOSKernelPath` with `Platform::GetOSKernelVersion` as was done for Linux.
* Update FreeBSD's `Platform::GetOSBuild` to report `uname`'s `release` string rather than `version`, as was previously done for Linux.
Confirmed the …
=> [gha] ensure the FreeBSD build job fails when there are compilation failures

Headers/DebugServer2/GDBRemote/DummySessionDelegateImpl.h, Headers/DebugServer2/GDBRemote/Mixins/FileOperationsMixin.h, Headers/DebugServer2/GDBRemote/SessionDelegate.h, Headers/DebugServer2/Host/File.h, Sources/GDBRemote/DummySessionDelegateImpl.cpp, Sources/GDBRemote/Mixins/FileOperationsMixin.hpp, Sources/GDBRemote/Session.cpp, Sources/Host/POSIX/File.cpp, Sources/Host/Windows/File.cpp
Implement responses to the `vFile:mode` and `vFile:size` packets in ds2 platform and debug server sessions. Fully addresses issue #136.  
* Add `File::fileMode` support to the `Host::File` interface
* Implement the POSIX version of `Host::File::fileMode` using `stat(2)`
* Stub-out the Windows implementation of `Host::File::fileMode`
* Override and implement the existing `SessionDelegate::onFileGetSize` method in `FileOperationsMixin` to call the exiting `Host::File::fileSize` method
* Add a new `SessionDelegate::onFileGetMode` method and override it in `FileOperationsMixin` to call the new `Host::File::fileMode` method
* Fix error response of `vFile:size` to match the lldb documentation.
DS2 does not properly implement responses to the `vFile:mode` and `vFile:size` packets. These packets …
=> implement support for `vFile:mode` and `vFile:size` packets

Headers/DebugServer2/GDBRemote/DummySessionDelegateImpl.h, Headers/DebugServer2/GDBRemote/Mixins/FileOperationsMixin.h, Headers/DebugServer2/GDBRemote/SessionDelegate.h, Headers/DebugServer2/Host/File.h, Sources/GDBRemote/DummySessionDelegateImpl.cpp, Sources/GDBRemote/Mixins/FileOperationsMixin.hpp, Sources/GDBRemote/Session.cpp, Sources/Host/POSIX/File.cpp, Sources/Host/Windows/File.cpp
Add support for lldb's `vFile:fstat` packet to ds2 debug and platform sessions. Fixes #135. 
* Add `fstat` method to the `File` class and implement it for POSIX. Leave the Windows implementation unimplemented (as is the rest of `File`)
* Call the new `File::fstat` method when is `vFile:fstat` packet is received.
Several of the lldb tests rely on `vFile:fstat` to fetch files from the device, and these tests fail against ds2 because it is not implemented.
The `vFile:fstat` packet isn't documented. The implementation is based on the expectation of the lldb test case `TestGdbRemotePlatformFile.TestGdbRemotePlatformFile.test_platform_file_fstat_llgs`, which now passes with this change.
Once this PR and a some additionalchanges are merged, most of the `TestGdbRemotePlatformFile` tests succeed …
=> add support for the vFile:fstat packet

Sources/Host/POSIX/ProcessSpawner.cpp, Sources/Target/POSIX/Process.cpp
Remove the call to `setsid(2)` on every process spawn and make debug inferior process setup items specific to `DebugSession` launched process. This PR makes ds2 process launch behavior consistent with lldb-server. Addresses issue #137 along with PR #143. 
* Eliminate the call to `setsid(2)` from `ProcessSpawner`
* Call `setpgid(2)` from the `preExecAction` callback for `DebugSession` process launch. Do not make this call for generic process launch (which again matches `lldb-server`'s behavior).
* Move the call to `setgid(2)` from the `ProcessSpawner` implementation into the `preExecAction` callback for `DebugSession` process launch. This move avoids making the call when launching processes that are not debug targets.
It is unclear why there was a call to `setsid(2)` on every process …
=> [posix] remove setgid(2)/setsid(2) from ProcessSpawner

Sources/Utils/Backtrace.cpp, Tools/JSObjects/CMakeLists.txt
* Set `-Wno-macro-redefined` when building JSObjects because the code generated by flex/bison generates this warning
* Gate backtrace implementation with `PLATFORM_ANDROID` because `ANDROID` is not defined when building for Windows
=> fix build issues when building for Android on Windows

Headers/DebugServer2/GDBRemote/DebugSessionImpl.h, Headers/DebugServer2/Host/POSIX/ProcessSpawner.h, Headers/DebugServer2/Host/Windows/ProcessSpawner.h, Sources/GDBRemote/DebugSessionImpl.cpp, Sources/GDBRemote/Session.cpp
Add support for GDB's `vRun` packet to ds2 debug sessions. Fixes issue #150. 
* Override `SessionDelegate::onRunAttach` in `DebugSession`. Use existing `spawnProcess` method to actually launch the process.
* Preserve environment variables set on `_spawner` by previous calls to `onSetEnvironmentVariable`.
* Preserve previous executable and arguments set on `_spawner` from previous calls to `onRunAttach`.
* Update `spawnProcess` to use memoized executable, arguments, and environment when new ones are not provided.
* Fix missing `index++` in `Session::Handle_vRun.
The following test cases rely on the `vRun` packet to work properly in the debug session:
```
GdbRemoteLaunchTestCase.test_QEnvironmentHexEncoded_llgs
GdbRemoteLaunchTestCase.test_QEnvironment_llgs …
```
=> add support for the vRun GDB packet

Headers/DebugServer2/GDBRemote/DummySessionDelegateImpl.h, Headers/DebugServer2/GDBRemote/Mixins/ProcessLaunchMixin.h, Headers/DebugServer2/GDBRemote/PlatformSessionImpl.h, Headers/DebugServer2/GDBRemote/SessionDelegate.h, Headers/DebugServer2/Host/Platform.h, Sources/GDBRemote/DummySessionDelegateImpl.cpp, Sources/GDBRemote/Mixins/ProcessLaunchMixin.hpp, Sources/GDBRemote/PlatformSessionImpl.cpp, Sources/GDBRemote/Session.cpp, Sources/Host/POSIX/Platform.cpp, Sources/Host/Windows/Platform.cpp
Add proper support for the `A` packet (program arguments) in the platform session implementation, launching programs on request from the connected debugger. Along with PR #146, addresses issue #137. 
* Implement `ProcessLaunchMixin::onSetProgramArguments` to spawn the specified executable with stdio and environment variables memoized in previous calls to `onSetStdFile` and `onSetEnvironmentVariable`. Use the existing `ProcessSpawner` implementation for the heavy lifting.
* Implement `ProcessLaunchMixin::onQueryProcessInfo` to enable the debugger to get details about the most recently launched process. Reuse the exiting `Platform::GetProcessInfo` function to retrieve the process information.
* Rename the pid-based `SessionDelegate::onQueryProcessInfo` method to …
=> fix the platform session process launch implementation

Sources/GDBRemote/Mixins/FileOperationsMixin.hpp, Sources/GDBRemote/Structures.cpp
The ds2 implementation for handling the `qModuleInfo` packet fails when it is unable to retrieve an ELF build ID from the module. This failure causes `lldb` to stop fetching info for subsequent modules. This PR addresses the issue by making `qModuleInfo` succeed in this case and excluding the `uuid` field from the response.
GitHub build & test
Locally verified debugging a Swift test that imports modules w/out build IDs. Images for all modules with build IDs load and symbols resolve correctly.
=> succeed `qModuleInfo` when ELF file has no build ID

.github/workflows/build.yml
Reduce the unnecessary logging produced when running `lldb-dotest`.
* Suppress `stdout` when running `lldb-dotest` since all of the useful output, including pass/fail logs, goes to `stderr`
* Reduces the log size so that they entirely fit in the GitHub log view page-- there is no need to download the log archive to find which test case failed
* Reduces the test run time by multiple minutes
Run GitHub build & test job on this PR.
=> [gha] remove `stdout` from test logs to reduce verbosity

Sources/Target/POSIX/ELFProcess.cpp
Check the link audit version the ELF debug header is not greater than the current version, `LAV_CURRENT` rather than exactly equal to it.
On a recent Linux host, `LAV_CURRENT` is defined as 2, while modules may be 1 or 2. Changing the check this way allows both v1 and v2 modules to load, which is safe since the header layouts did not between versions.
Manually ran `image list` from lldb when attached to a `remote-linux` ds2 server (on Fedora 40) and verified the list of modules matches the list generated when doing the same against an lldb-server instance.
=> allow ELF link audit version <= LAV_CURRENT

README.md
Cleanup and enhance the README file for build and running ds2 on Android.
* Clarify how to build with the Android NDK and for Android in general
* Add instructions on running on Android, using adb, etc
* Add instructions on running in platform mode
* Overall cleanup
Inspected the rendered contents [here](https://github.com/andrurogerz/ds2/tree/cleanup-readme).
=> [android] update README for building and running on Android

.github/workflows/build.yml
Add lzma support to the version of lldb built to run lldb tests against ds2. This addition eliminates the following warnings that previously appeared when running the tests on Android:
```
warning: (x86_64) /home/runner/.lldb/module_cache/remote-android/.cache/27659E9D-B4F4-B4D2-71C0-6A6D79C81CBA/libm.so No LZMA support found for reading .gnu_debugdata section
warning: (x86_64) /home/runner/.lldb/module_cache/remote-android/.cache/32A6676D-6870-2632-466C-E517D9C8E3DF/libdl.so No LZMA support found for reading .gnu_debugdata section
warning: (x86_64) /home/runner/.lldb/module_cache/remote-android/.cache/896BBDB3-DFDF-EF7E-4E56-BCF87BE1517D/libnetd_client.so No LZMA support found for reading .gnu_debugdata section
warning: (x86_64) …
```
=> [gha] build lldb with lzma enabled

CMakeLists.txt
This project uses spaces for indentation not tabs. Convert some of the tabs to spaces.
=> build: replace tabs with spaces (NFC)

CMakeLists.txt
This new option emulates `--program-prefix` from autotools. This is intended to help with installation of cross-compiled binaries for ds2.
=> build: allow adding a program prefix for ds2

.github/workflows/build.yml
Add the `-v` option when running `lldb-dotest` so that the name of each test case is logged prior to running the test.
Example:
```
472: test_debugger_interrupt_use_dbg (TestDebuggerInterruption.TestDebuggerInterruption.test_debugger_interrupt_use_dbg) ... ok
PASS: LLDB (/home/runner/work/ds2/ds2/BinaryCache/llvm/bin/clang-i686) :: test_debugger_interrupt_use_dbg (TestDebuggerInterruption.TestDebuggerInterruption.test_debugger_interrupt_use_dbg)
```
This logging will help to identify test cases that occasionally hang so we can disable them.
=> [gha] enable test case name logging

Android.md
Add a howto doc for using ds2 and lldb to debug Android applications.
The rendered version can be viewed on my fork [here](https://github.com/andrurogerz/ds2/blob/android-debugging-docs/Android.md).
=> [android] add documentation for debugging Android with ds2

.gitignore
This directory is referenced in the documentation as the default output
location. Ignore this location as a potential build tree.
=> git: ignore `/out/`

CMakeLists.txt
Bump the required CMake version to 3.25 as we are using the `LINUX` variable
which was introduced in 3.25. This ensures that we build properly on Linux by
preventing use of an older CMake where certain sources and checks may be
otherwise elided.
=> build: bump CMake requirement to 3.25

Sources/Utils/POSIX/FaultHandler.cpp
`_SC_SIGSTKSZ` was introduced in a semi-recent glibc version. Provide a fallback
for older glibc environments so that we can support a broader set of Linux
environments.
=> POSIX: provide compatibility for older Linux environments

Headers/DebugServer2/Base.h, Sources/Target/Common/ProcessBase.cpp, Sources/Target/POSIX/Process.cpp, Sources/Target/Windows/Process.cpp, Sources/main.cpp
We currently use C++17 as the C++ standard. Remove compatibility shims to enable
building with C++11.
=> Headers: remove C++14 compatibility shim

.github/workflows/build.yml
A couple of minor fixes to address broken github action:
* Call `apt-get update` before installing lzma packages
* Update the lzma package install command to match other package install commands (use `apt-get` and quiet options)
=> [gha] fix lzma package install commands

Tools/JSObjects/CMakeLists.txt
Bump the min required CMake version for JSObjects to 3.10. This avoids errors and warnings when building with CMake versions >= 4.0 which no longer support syntax < version 3.5 and warn on < version 3.10.
I observed these failures a few time in nightly runs, but they are not consistent. It seems like some of the GitHub runners have newer CMake versions.
https://github.com/andrurogerz/ds2/actions/runs/14258245061/job/39964714091
https://github.com/andrurogerz/ds2/actions/runs/14235199194/job/39893148054
https://github.com/andrurogerz/ds2/actions/runs/14211762613/job/39820138528
=> [cmake] update JSObjects CMake minimum version to 3.10

README.md
Add a flat list of supported debugging platforms. This should aide users looking to see if a particular platform is supported by DS2.
Clarify that regsgen2 and libjson are not distributed as part of the DS2 distribution.
Add a small blurb indicating that contributions are welcome.
=> docs: improve README content

README.md
Sort by architecture instead of OS. This gives a better understanding of what possible coverage DS2 can host. Add a footnote to indicate that Tizen is currently not being tested in CI.
=> docs: update platform status
